I1216 02:23:50.444312 140613273249536 hlog.py:32] train 549
I1216 02:23:50.444531 140613273249536 hlog.py:32] aug 0
Traceback (most recent call last):
  File "../../compose.py", line 107, in <module>
    app.run(main)
  File "/x/jda/anaconda3/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/x/jda/anaconda3/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "../../compose.py", line 67, in main
    datum = make_batch([(templ, templ) for _ in range(10)], dataset.vocab, staged=True)
  File "/x/jda/metacomp2/trainer.py", line 29, in make_batch
    ref, tgt, extra = seqs
ValueError: not enough values to unpack (expected 3, got 2)
